import pandas as pd
import matplotlib.pyplot as plt
import os
import subprocess

# Column names for the dataset
col_names = [
    'age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg',
    'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'
]

def generate_chart(df, charts_dir):
    os.makedirs(charts_dir, exist_ok=True)
    chart_path = os.path.join(charts_dir, 'age_distribution.png')
    
    plt.figure(figsize=(8, 5))
    df['age'].hist(bins=10, color='skyblue', edgecolor='black')
    plt.title('Age Distribution of Heart Patients')
    plt.xlabel('Age')
    plt.ylabel('Count')
    plt.tight_layout()
    plt.savefig(chart_path)
    plt.close()
    
    return chart_path

def generate_latex(df, chart_path, output_dir):
    os.makedirs(output_dir, exist_ok=True)
    tex_path = os.path.join(output_dir, 'report.tex')

    # Generate simple stats for summary table
    mean_age = df['age'].mean()
    median_age = df['age'].median()
    count = len(df)

    latex_content = rf"""
\documentclass{{article}}
\usepackage{{graphicx}}
\usepackage{{booktabs}}
\usepackage[margin=1in]{{geometry}}
\begin{{document}}

\title{{Heart Disease Report}}
\author{{Generated by PDFReportGenerator}}
\date{{\today}}
\maketitle

\section*{{Summary Statistics}}
\begin{{tabular}}{{lr}}
\toprule
Total patients & {count} \\
Mean age & {mean_age:.1f} \\
Median age & {median_age:.1f} \\
\bottomrule
\end{{tabular}}

\section*{{Age Distribution Chart}}
\begin{{figure}}[h!]
    \centering
    \includegraphics[width=0.8\linewidth]{{{os.path.basename(chart_path)}}}
    \caption{{Age Distribution of Patients}}
\end{{figure}}

\end{{document}}
"""

    with open(tex_path, 'w') as f:
        f.write(latex_content)
    
    return tex_path

def compile_pdf(tex_path, working_dir):
    # Run pdflatex twice to ensure proper references (optional for this simple doc)
    subprocess.run(['pdflatex', '-interaction=nonstopmode', tex_path], cwd=working_dir)
    subprocess.run(['pdflatex', '-interaction=nonstopmode', tex_path], cwd=working_dir)

def main():
    path = './data/heart_cleveland.csv'
    charts_dir = './charts'
    report_dir = './report'

    if not os.path.exists(path):
        print(f"File not found at {path}")
        return

    df = pd.read_csv(path, names=col_names)
    print("Data loaded successfully!")
    print(df.head())

    # Generate chart
    chart_path = generate_chart(df, charts_dir)
    print(f"Chart saved at {chart_path}")

    # Copy the chart image to report directory (needed for LaTeX to find it)
    os.makedirs(report_dir, exist_ok=True)
    chart_report_path = os.path.join(report_dir, os.path.basename(chart_path))
    if chart_path != chart_report_path:
        import shutil
        shutil.copy(chart_path, chart_report_path)

    # Generate LaTeX file
    tex_path = generate_latex(df, chart_report_path, report_dir)
    print(f"LaTeX file created at {tex_path}")

    # Compile PDF
    compile_pdf(os.path.basename(tex_path), report_dir)
    print(f"PDF report generated at {os.path.join(report_dir, 'report.pdf')}")

if __name__ == '__main__':
    main()
